"""Pydantic schemas initialization"""
from .common import APIResponse, PaginatedData
from .user import (
    UserRole,
    UserRegister,
    UserLogin,
    TokenRefreshRequest,
    ForgotPasswordRequest,
    ResetPasswordRequest,
    UserProfileUpdate,
    PasswordChangeRequest,
    UserResponse,
    AuthResponse,
)
from .wallet import (
    TransactionType,
    TransactionStatus,
    PointTransactionResponse,
    WalletResponse,
    AdminPointsAdjustment,
)
from .task import (
    TaskCategory,
    TaskDifficulty,
    TaskStatus,
    TaskCreate,
    TaskUpdate,
    TaskResponse,
    TaskSubmissionCreate,
    TaskSubmissionResponse,
)
from .quiz import (
    QuestionType,
    QuizQuestionCreate,
    QuizQuestionSafe,
    QuizQuestionDetail,
    QuizCreate,
    QuizUpdate,
    QuizListItem,
    QuizPlayResponse,
    QuizSubmitRequest,
    QuizResultResponse,
    QuestionResultReview,
)
from .reward import (
    RewardType,
    RewardStatus,
    RewardCreate,
    RewardUpdate,
    RewardResponse,
    RedemptionCreate,
    RedemptionResponse,
)
from .withdrawal import (
    WithdrawalMethod,
    WithdrawalStatus,
    WithdrawalCreate,
    WithdrawalResponse,
    WithdrawalActionRequest,
)
from .streak import (
    DailyStreakResponse,
    StreakClaimResponse,
    DailyStreakDayInfo,
)
from .social import (
    ReferralDashboardResponse,
    ReferralUserItem,
    LeaderboardEntry,
    LeaderboardResponse,
    AchievementItem,
    AchievementsListResponse,
)
from .notification import NotificationResponse, NotificationCreate
from .admin import (
    AdminStatsResponse,
    AdminUserUpdateRequest,
    FraudEventResponse,
    FraudEventActionRequest,
    SystemSettingsSchema,
)

__all__ = [
    "APIResponse",
    "PaginatedData",
    "UserRole",
    "UserRegister",
    "UserLogin",
    "TokenRefreshRequest",
    "ForgotPasswordRequest",
    "ResetPasswordRequest",
    "UserProfileUpdate",
    "PasswordChangeRequest",
    "UserResponse",
    "AuthResponse",
    "TransactionType",
    "TransactionStatus",
    "PointTransactionResponse",
    "WalletResponse",
    "AdminPointsAdjustment",
    "TaskCategory",
    "TaskDifficulty",
    "TaskStatus",
    "TaskCreate",
    "TaskUpdate",
    "TaskResponse",
    "TaskSubmissionCreate",
    "TaskSubmissionResponse",
    "QuestionType",
    "QuizQuestionCreate",
    "QuizQuestionSafe",
    "QuizQuestionDetail",
    "QuizCreate",
    "QuizUpdate",
    "QuizListItem",
    "QuizPlayResponse",
    "QuizSubmitRequest",
    "QuizResultResponse",
    "QuestionResultReview",
    "RewardType",
    "RewardStatus",
    "RewardCreate",
    "RewardUpdate",
    "RewardResponse",
    "RedemptionCreate",
    "RedemptionResponse",
    "WithdrawalMethod",
    "WithdrawalStatus",
    "WithdrawalCreate",
    "WithdrawalResponse",
    "WithdrawalActionRequest",
    "DailyStreakResponse",
    "StreakClaimResponse",
    "DailyStreakDayInfo",
    "ReferralDashboardResponse",
    "ReferralUserItem",
    "LeaderboardEntry",
    "LeaderboardResponse",
    "AchievementItem",
    "AchievementsListResponse",
    "NotificationResponse",
    "NotificationCreate",
    "AdminStatsResponse",
    "AdminUserUpdateRequest",
    "FraudEventResponse",
    "FraudEventActionRequest",
    "SystemSettingsSchema",
]
